local GAFE = GroupActivityFinderExtensions

GAFE_LFG_ACTIVITY_TRIAL = LFG_ACTIVITY_ITERATION_END + 1
GAFE_LFG_ACTIVITY_MASTER_TRIAL = LFG_ACTIVITY_ITERATION_END + 2
GAFE_ACTIVITY_FINDER_SORT_PRIORITY = {
	ACTIVITY_SCHEDULE = ZO_ACTIVITY_FINDER_SORT_PRIORITY.DUNGEONS + 1000,
	TRIALS = ZO_ACTIVITY_FINDER_SORT_PRIORITY.DUNGEONS + 50
}
