-- https://esoitem.uesp.net/viewlog.php
local GAFE = GroupActivityFinderExtensions

-- n_id: Normal achievement ID, v_id: Veteran achievement ID
local TRIAL_CONFIGS = {
  { lf = "AA",  normal = GAFE.ACTIVITY_ID.NormalAetherianArchive,   n_id = 990,  n_hm = 1137, n_tt = 1081, veteran = GAFE.ACTIVITY_ID.VeteranAetherianArchive,   v_id = 1503, v_hm = false, v_tt = false, v_nd = false, node = 231, q = 5102, sets = { GAFE.SET_ID.DefendingWarrior, GAFE.SET_ID.HealingMage, GAFE.SET_ID.InfallibleMage, GAFE.SET_ID.QuickSerpent } },
  { lf = "HRC", normal = GAFE.ACTIVITY_ID.NormalHelRaCitadel,        n_id = 991,  n_hm = 1136, n_tt = 1080, veteran = GAFE.ACTIVITY_ID.VeteranHelRaCitadel,        v_id = 1474, v_hm = 870,   v_tt = false, v_nd = false, node = 230, q = 5087, sets = { GAFE.SET_ID.BerserkingWarrior, GAFE.SET_ID.DestructiveMage, GAFE.SET_ID.EternalWarrior, GAFE.SET_ID.PoisonousSerpent } },
  { lf = "SO",  normal = GAFE.ACTIVITY_ID.NormalSanctumOphidia,      n_id = 1123, n_hm = 1138, n_tt = 1124, veteran = GAFE.ACTIVITY_ID.VeteranSanctumOphidia,      v_id = 1462, v_hm = false, v_tt = false, v_nd = false, node = 232, q = 5171, sets = { GAFE.SET_ID.ImmortalWarrior, GAFE.SET_ID.TwiceFangedSerpent, GAFE.SET_ID.ViciousSerpent, GAFE.SET_ID.WiseMage } },
  { lf = "MOL", normal = GAFE.ACTIVITY_ID.NormalMawOfLorkhaj,        n_id = 1343, n_hm = false, n_tt = false, veteran = GAFE.ACTIVITY_ID.VeteranMawOfLorkhaj,       v_id = 1368, v_hm = 1344,  v_tt = 1368,  v_nd = 1368,  node = 258, q = 5352, sets = { GAFE.SET_ID.LunarBastion, GAFE.SET_ID.Moondancer, GAFE.SET_ID.RoarofAlkosh, GAFE.SET_ID.TwilightRemedy } },
  { lf = "HOF", normal = GAFE.ACTIVITY_ID.NormalHallsOfFabrication,  n_id = 1808, n_hm = false, n_tt = false, veteran = GAFE.ACTIVITY_ID.VeteranHallsOfFabrication, v_id = 1810, v_hm = 1829,  v_tt = 1809,  v_nd = 1811,  node = 331, q = 5894, sets = { GAFE.SET_ID.AutomatedDefense, GAFE.SET_ID.InventorsGuard, GAFE.SET_ID.MasterArchitect, GAFE.SET_ID.WarMachine } },
  { lf = "AS",  normal = GAFE.ACTIVITY_ID.NormalAsylumSanctorium,    n_id = 2076, n_hm = 2078,  n_tt = false, veteran = GAFE.ACTIVITY_ID.VeteranAsylumSanctorium,   v_id = 2077, v_hm = 2079,  v_tt = 2081,  v_nd = 2080,  node = 346, q = 6090, sets = { GAFE.SET_ID.ChaoticWhirlwind, GAFE.SET_ID.PerfectedChaoticWhirlwind, GAFE.SET_ID.ConcentratedForce, GAFE.SET_ID.PerfectedConcentratedForce, GAFE.SET_ID.DefensivePosition, GAFE.SET_ID.PerfectedDefensivePosition, GAFE.SET_ID.DisciplinedSlash, GAFE.SET_ID.PerfectedDisciplinedSlash, GAFE.SET_ID.PiercingSpray, GAFE.SET_ID.PerfectedPiercingSpray, GAFE.SET_ID.TimelessBlessing, GAFE.SET_ID.PerfectedTimelessBlessing } },
  { lf = "CR",  normal = GAFE.ACTIVITY_ID.NormalCloudrest,           n_id = 2131, n_hm = 2132,  n_tt = false, veteran = GAFE.ACTIVITY_ID.VeteranCloudrest,          v_id = 2133, v_hm = 2136,  v_tt = 2137,  v_nd = 2138,  node = 364, q = 6192, sets = { GAFE.SET_ID.AegisofGalenwe, GAFE.SET_ID.PerfectedAegisofGalenwe, GAFE.SET_ID.ArmsofRelequen, GAFE.SET_ID.PerfectedArmsofRelequen, GAFE.SET_ID.MantleofSiroria, GAFE.SET_ID.PerfectedMantleofSiroria, GAFE.SET_ID.VestmentofOlorime, GAFE.SET_ID.PerfectedVestmentofOlorime } },
  { lf = "SS",  normal = GAFE.ACTIVITY_ID.NormalSunspire,            n_id = 2433, n_hm = false, n_tt = false, veteran = GAFE.ACTIVITY_ID.VeteranSunspire,            v_id = 2435, v_hm = 2466,  v_tt = 2434,  v_nd = 2436,  node = 399, q = 6353, sets = { GAFE.SET_ID.ClawofYolnahkriin, GAFE.SET_ID.PerfectedClawofYolnahkriin, GAFE.SET_ID.EyeofNahviintaas, GAFE.SET_ID.PerfectedEyeofNahviintaas, GAFE.SET_ID.FalseGodsDevotion, GAFE.SET_ID.PerfectedFalseGodsDevotion, GAFE.SET_ID.ToothofLokkestiiz, GAFE.SET_ID.PerfectedToothofLokkestiiz } },
  { lf = "KA",  normal = GAFE.ACTIVITY_ID.NormalKynesAegis,          n_id = 2732, n_hm = false, n_tt = false, veteran = GAFE.ACTIVITY_ID.VeteranKynesAegis,          v_id = 2734, v_hm = 2739,  v_tt = 2733,  v_nd = 2735,  node = 434, q = 6503, sets = { GAFE.SET_ID.KynesWind, GAFE.SET_ID.PerfectedKynesWind, GAFE.SET_ID.RoaringOpportunist, GAFE.SET_ID.PerfectedRoaringOpportunist, GAFE.SET_ID.VrolsCommand, GAFE.SET_ID.PerfectedVrolsCommand, GAFE.SET_ID.YandirsMight, GAFE.SET_ID.PerfectedYandirsMight } },
  { lf = "RG",  normal = GAFE.ACTIVITY_ID.NormalRockgrove,           n_id = 2985, n_hm = false, n_tt = false, veteran = GAFE.ACTIVITY_ID.VeteranRockgrove,           v_id = 2987, v_hm = 3007,  v_tt = 2986,  v_nd = 2988,  node = 468, q = 6654, sets = { GAFE.SET_ID.BahseisMania, GAFE.SET_ID.PerfectedBahseisMania, GAFE.SET_ID.SaxhleelChampion, GAFE.SET_ID.PerfectedSaxhleelChampion, GAFE.SET_ID.StoneTalkersOath, GAFE.SET_ID.PerfectedStoneTalkersOath, GAFE.SET_ID.SulXansTorment, GAFE.SET_ID.PerfectedSulXansTorment } },
  { lf = "DR",  normal = GAFE.ACTIVITY_ID.NormalDreadsailReef,       n_id = 3242, n_hm = false, n_tt = false, veteran = GAFE.ACTIVITY_ID.VeteranDreadsailReef,       v_id = 3244, v_hm = 3250,  v_tt = 3243,  v_nd = 3245,  node = 488, q = 6783, sets = { GAFE.SET_ID.CoralRiptide, GAFE.SET_ID.PerfectedCoralRiptide, GAFE.SET_ID.PearlescentWard, GAFE.SET_ID.PerfectedPearlescentWard, GAFE.SET_ID.PillagersProfit, GAFE.SET_ID.PerfectedPillagersProfit, GAFE.SET_ID.WhorloftheDepths, GAFE.SET_ID.PerfectedWhorloftheDepths } },
}

local TRIALS_ACTIVITY_DATA = {}
for _, t in ipairs(TRIAL_CONFIGS) do
  TRIALS_ACTIVITY_DATA[t.normal]  = { lf = "n" .. t.lf, node = t.node, q = t.q, id = t.n_id, hm = t.n_hm, tt = t.n_tt, nd = false,  sets = t.sets }
  TRIALS_ACTIVITY_DATA[t.veteran] = { lf = "v" .. t.lf, node = t.node, q = t.q, id = t.v_id, hm = t.v_hm, tt = t.v_tt, nd = t.v_nd, sets = t.sets }
end

GAFE.TRIALS_ACTIVITY_DATA = TRIALS_ACTIVITY_DATA
