-- https://esoitem.uesp.net/viewlog.php
local GAFE = GroupActivityFinderExtensions

local TRIALS_ACTIVITY_DATA = {
    --Normal
    [GAFE.ACTIVITY_ID.NormalAetherianArchive]    = { lf = "nAA", node = 231, q = 5102, id = 990, hm = 1137, tt = 1081, nd = false, sets = { GAFE.SET_ID.DefendingWarrior, GAFE.SET_ID.HealingMage, GAFE.SET_ID.InfallibleMage, GAFE.SET_ID.QuickSerpent } },
    [GAFE.ACTIVITY_ID.NormalHelRaCitadel]        = { lf = "nHRC", node = 230, q = 5087, id = 991, hm = 1136, tt = 1080, nd = false, sets = { GAFE.SET_ID.BerserkingWarrior, GAFE.SET_ID.DestructiveMage, GAFE.SET_ID.EternalWarrior, GAFE.SET_ID.PoisonousSerpent } },
    [GAFE.ACTIVITY_ID.NormalSanctumOphidia]      = { lf = "nSO", node = 232, q = 5171, id = 1123, hm = 1138, tt = 1124, nd = false, sets = { GAFE.SET_ID.ImmortalWarrior, GAFE.SET_ID.TwiceFangedSerpent, GAFE.SET_ID.ViciousSerpent, GAFE.SET_ID.WiseMage } },
    [GAFE.ACTIVITY_ID.NormalMawOfLorkhaj]        = { lf = "nMOL", node = 258, q = 5352, id = 1343, hm = false, tt = false, nd = false, sets = { GAFE.SET_ID.LunarBastion, GAFE.SET_ID.Moondancer, GAFE.SET_ID.RoarofAlkosh, GAFE.SET_ID.TwilightRemedy } },
    [GAFE.ACTIVITY_ID.NormalHallsOfFabrication]  = { lf = "nHOF", node = 331, q = 5894, id = 1808, hm = false, tt = false, nd = false, sets = { GAFE.SET_ID.AutomatedDefense, GAFE.SET_ID.InventorsGuard, GAFE.SET_ID.MasterArchitect, GAFE.SET_ID.WarMachine } },
    [GAFE.ACTIVITY_ID.NormalAsylumSanctorium]    = { lf = "nAS", node = 346, q = 6090, id = 2076, hm = 2078, tt = false, nd = false, sets = { GAFE.SET_ID.ChaoticWhirlwind, GAFE.SET_ID.PerfectedChaoticWhirlwind, GAFE.SET_ID.ConcentratedForce, GAFE.SET_ID.PerfectedConcentratedForce, GAFE.SET_ID.DefensivePosition, GAFE.SET_ID.PerfectedDefensivePosition, GAFE.SET_ID.DisciplinedSlash, GAFE.SET_ID.PerfectedDisciplinedSlash, GAFE.SET_ID.PiercingSpray, GAFE.SET_ID.PerfectedPiercingSpray, GAFE.SET_ID.TimelessBlessing, GAFE.SET_ID.PerfectedTimelessBlessing } },
    [GAFE.ACTIVITY_ID.NormalCloudrest]           = { lf = "nCR", node = 364, q = 6192, id = 2131, hm = 2132, tt = false, nd = false, sets = { GAFE.SET_ID.AegisofGalenwe, GAFE.SET_ID.PerfectedAegisofGalenwe, GAFE.SET_ID.ArmsofRelequen, GAFE.SET_ID.PerfectedArmsofRelequen, GAFE.SET_ID.MantleofSiroria, GAFE.SET_ID.PerfectedMantleofSiroria, GAFE.SET_ID.VestmentofOlorime, GAFE.SET_ID.PerfectedVestmentofOlorime } },
    [GAFE.ACTIVITY_ID.NormalSunspire]            = { lf = "nSS", node = 399, q = 6353, id = 2433, hm = false, tt = false, nd = false, sets = { GAFE.SET_ID.ClawofYolnahkriin, GAFE.SET_ID.PerfectedClawofYolnahkriin, GAFE.SET_ID.EyeofNahviintaas, GAFE.SET_ID.PerfectedEyeofNahviintaas, GAFE.SET_ID.FalseGodsDevotion, GAFE.SET_ID.PerfectedFalseGodsDevotion, GAFE.SET_ID.ToothofLokkestiiz, GAFE.SET_ID.PerfectedToothofLokkestiiz } },
    [GAFE.ACTIVITY_ID.NormalKynesAegis]          = { lf = "nKA", node = 434, q = 6503, id = 2732, hm = false, tt = false, nd = false, sets = { GAFE.SET_ID.KynesWind, GAFE.SET_ID.PerfectedKynesWind, GAFE.SET_ID.RoaringOpportunist, GAFE.SET_ID.PerfectedRoaringOpportunist, GAFE.SET_ID.VrolsCommand, GAFE.SET_ID.PerfectedVrolsCommand, GAFE.SET_ID.YandirsMight, GAFE.SET_ID.PerfectedYandirsMight } },
    [GAFE.ACTIVITY_ID.NormalRockgrove]           = { lf = "nRG", node = 468, q = 6654, id = 2985, hm = false, tt = false, nd = false, sets = { GAFE.SET_ID.BahseisMania, GAFE.SET_ID.PerfectedBahseisMania, GAFE.SET_ID.SaxhleelChampion, GAFE.SET_ID.PerfectedSaxhleelChampion, GAFE.SET_ID.StoneTalkersOath, GAFE.SET_ID.PerfectedStoneTalkersOath, GAFE.SET_ID.SulXansTorment, GAFE.SET_ID.PerfectedSulXansTorment } },
    [GAFE.ACTIVITY_ID.NormalDreadsailReef]       = { lf = "nDR", node = 488, q = 6783, id = 3242, hm = false, tt = false, nd = false, sets = { GAFE.SET_ID.CoralRiptide, GAFE.SET_ID.PerfectedCoralRiptide, GAFE.SET_ID.PearlescentWard, GAFE.SET_ID.PerfectedPearlescentWard, GAFE.SET_ID.PillagersProfit, GAFE.SET_ID.PerfectedPillagersProfit, GAFE.SET_ID.WhorloftheDepths, GAFE.SET_ID.PerfectedWhorloftheDepths } },
    --Veteran
    [GAFE.ACTIVITY_ID.VeteranAetherianArchive]   = { lf = "vAA", node = 231, q = 5102, id = 1503, hm = false, tt = false, nd = false, sets = { GAFE.SET_ID.DefendingWarrior, GAFE.SET_ID.HealingMage, GAFE.SET_ID.InfallibleMage, GAFE.SET_ID.QuickSerpent } },
    [GAFE.ACTIVITY_ID.VeteranHelRaCitadel]       = { lf = "vHRC", node = 230, q = 5087, id = 1474, hm = 870, tt = false, nd = false, sets = { GAFE.SET_ID.BerserkingWarrior, GAFE.SET_ID.DestructiveMage, GAFE.SET_ID.EternalWarrior, GAFE.SET_ID.PoisonousSerpent } },
    [GAFE.ACTIVITY_ID.VeteranSanctumOphidia]     = { lf = "vSO", node = 232, q = 5171, id = 1462, hm = false, tt = false, nd = false, sets = { GAFE.SET_ID.ImmortalWarrior, GAFE.SET_ID.TwiceFangedSerpent, GAFE.SET_ID.ViciousSerpent, GAFE.SET_ID.WiseMage } },
    [GAFE.ACTIVITY_ID.VeteranMawOfLorkhaj]       = { lf = "vMOL", node = 258, q = 5352, id = 1368, hm = 1344, tt = 1368, nd = 1368, sets = { GAFE.SET_ID.LunarBastion, GAFE.SET_ID.Moondancer, GAFE.SET_ID.RoarofAlkosh, GAFE.SET_ID.TwilightRemedy } },
    [GAFE.ACTIVITY_ID.VeteranHallsOfFabrication] = { lf = "vHOF", node = 331, q = 5894, id = 1810, hm = 1829, tt = 1809, nd = 1811, sets = { GAFE.SET_ID.AutomatedDefense, GAFE.SET_ID.InventorsGuard, GAFE.SET_ID.MasterArchitect, GAFE.SET_ID.WarMachine } },
    [GAFE.ACTIVITY_ID.VeteranAsylumSanctorium]   = { lf = "vAS", node = 346, q = 6090, id = 2077, hm = 2079, tt = 2081, nd = 2080, sets = { GAFE.SET_ID.ChaoticWhirlwind, GAFE.SET_ID.PerfectedChaoticWhirlwind, GAFE.SET_ID.ConcentratedForce, GAFE.SET_ID.PerfectedConcentratedForce, GAFE.SET_ID.DefensivePosition, GAFE.SET_ID.PerfectedDefensivePosition, GAFE.SET_ID.DisciplinedSlash, GAFE.SET_ID.PerfectedDisciplinedSlash, GAFE.SET_ID.PiercingSpray, GAFE.SET_ID.PerfectedPiercingSpray, GAFE.SET_ID.TimelessBlessing, GAFE.SET_ID.PerfectedTimelessBlessing } },
    [GAFE.ACTIVITY_ID.VeteranCloudrest]          = { lf = "vCR", node = 364, q = 6192, id = 2133, hm = 2136, tt = 2137, nd = 2138, sets = { GAFE.SET_ID.AegisofGalenwe, GAFE.SET_ID.PerfectedAegisofGalenwe, GAFE.SET_ID.ArmsofRelequen, GAFE.SET_ID.PerfectedArmsofRelequen, GAFE.SET_ID.MantleofSiroria, GAFE.SET_ID.PerfectedMantleofSiroria, GAFE.SET_ID.VestmentofOlorime, GAFE.SET_ID.PerfectedVestmentofOlorime } },
    [GAFE.ACTIVITY_ID.VeteranSunspire]           = { lf = "vSS", node = 399, q = 6353, id = 2435, hm = 2466, tt = 2434, nd = 2436, sets = { GAFE.SET_ID.ClawofYolnahkriin, GAFE.SET_ID.PerfectedClawofYolnahkriin, GAFE.SET_ID.EyeofNahviintaas, GAFE.SET_ID.PerfectedEyeofNahviintaas, GAFE.SET_ID.FalseGodsDevotion, GAFE.SET_ID.PerfectedFalseGodsDevotion, GAFE.SET_ID.ToothofLokkestiiz, GAFE.SET_ID.PerfectedToothofLokkestiiz } },
    [GAFE.ACTIVITY_ID.VeteranKynesAegis]         = { lf = "vKA", node = 434, q = 6503, id = 2734, hm = 2739, tt = 2733, nd = 2735, sets = { GAFE.SET_ID.KynesWind, GAFE.SET_ID.PerfectedKynesWind, GAFE.SET_ID.RoaringOpportunist, GAFE.SET_ID.PerfectedRoaringOpportunist, GAFE.SET_ID.VrolsCommand, GAFE.SET_ID.PerfectedVrolsCommand, GAFE.SET_ID.YandirsMight, GAFE.SET_ID.PerfectedYandirsMight } },
    [GAFE.ACTIVITY_ID.VeteranRockgrove]          = { lf = "vRG", node = 468, q = 6654, id = 2987, hm = 3007, tt = 2986, nd = 2988, sets = { GAFE.SET_ID.BahseisMania, GAFE.SET_ID.PerfectedBahseisMania, GAFE.SET_ID.SaxhleelChampion, GAFE.SET_ID.PerfectedSaxhleelChampion, GAFE.SET_ID.StoneTalkersOath, GAFE.SET_ID.PerfectedStoneTalkersOath, GAFE.SET_ID.SulXansTorment, GAFE.SET_ID.PerfectedSulXansTorment } },
    [GAFE.ACTIVITY_ID.VeteranDreadsailReef]      = { lf = "vDR", node = 488, q = 6783, id = 3244, hm = 3250, tt = 3243, nd = 3245, sets = { GAFE.SET_ID.CoralRiptide, GAFE.SET_ID.PerfectedCoralRiptide, GAFE.SET_ID.PearlescentWard, GAFE.SET_ID.PerfectedPearlescentWard, GAFE.SET_ID.PillagersProfit, GAFE.SET_ID.PerfectedPillagersProfit, GAFE.SET_ID.WhorloftheDepths, GAFE.SET_ID.PerfectedWhorloftheDepths } },
}

GAFE.TRIALS_ACTIVITY_DATA = TRIALS_ACTIVITY_DATA
