-- https://esoitem.uesp.net/viewlog.php
-- id: Vanquisher/Conqueror Achievement ID, node: Wayshrine node IDs, q: Skill point quest ID, p: Pledge ID, hm: Hard Mode Achievement ID, tt: Trial Tracker Achievement ID, nd: No Death Achievement ID, sets: Set IDs
local GAFE = GroupActivityFinderExtensions

-- n_id: Normal achievement ID, v_id: Veteran achievement ID
local DUNGEON_CONFIGS = {
  --Normal
  { normal = GAFE.ACTIVITY_ID.NormalFungalGrottoI,      n_id = 294,   veteran = GAFE.ACTIVITY_ID.VeteranFungalGrottoI,      v_id = 1556, hm = 1561, tt = 1559, nd = 1560, node = 98,  q = 3993, p = 5247, sets = { GAFE.SET_ID.DreughKingSlayer, GAFE.SET_ID.SpiderCultistCowl, GAFE.SET_ID.VipersSting } },
  { normal = GAFE.ACTIVITY_ID.NormalFungalGrottoII,     n_id = 1562,  veteran = GAFE.ACTIVITY_ID.VeteranFungalGrottoII,     v_id = 343,  hm = 342,  tt = 340,  nd = 1563, node = 266, q = 4303, p = 5248, sets = { GAFE.SET_ID.DreughKingSlayer, GAFE.SET_ID.SpiderCultistCowl, GAFE.SET_ID.VipersSting } },
  { normal = GAFE.ACTIVITY_ID.NormalSpindleclutchI,     n_id = 301,   veteran = GAFE.ACTIVITY_ID.VeteranSpindleclutchI,     v_id = 1565, hm = 1570, tt = 1568, nd = 1569, node = 193, q = 4054, p = 5260, sets = { GAFE.SET_ID.Knightmare, GAFE.SET_ID.PrayerShawl, GAFE.SET_ID.Spelunker } },
  { normal = GAFE.ACTIVITY_ID.NormalSpindleclutchII,    n_id = 1571,  veteran = GAFE.ACTIVITY_ID.VeteranSpindleclutchII,    v_id = 421,  hm = 448,  tt = 446,  nd = 1572, node = 267, q = 4555, p = 5273, sets = { GAFE.SET_ID.Knightmare, GAFE.SET_ID.PrayerShawl, GAFE.SET_ID.Spelunker } },
  { normal = GAFE.ACTIVITY_ID.NormalBanishedCellsI,     n_id = 325,   veteran = GAFE.ACTIVITY_ID.VeteranBanishedCellsI,     v_id = 1549, hm = 1554, tt = 1552, nd = 1553, node = 194, q = 4107, p = 5244, sets = { GAFE.SET_ID.Jailbreaker, GAFE.SET_ID.Sanctuary, GAFE.SET_ID.Tormentor } },
  { normal = GAFE.ACTIVITY_ID.NormalBanishedCellsII,    n_id = 1555,  veteran = GAFE.ACTIVITY_ID.VeteranBanishedCellsII,    v_id = 545,  hm = 451,  tt = 449,  nd = 1564, node = 262, q = 4597, p = 5246, sets = { GAFE.SET_ID.Jailbreaker, GAFE.SET_ID.Sanctuary, GAFE.SET_ID.Tormentor } },
  { normal = GAFE.ACTIVITY_ID.NormalDarkshadeCavernsI,  n_id = 78,    veteran = GAFE.ACTIVITY_ID.VeteranDarkshadeCavernsI,  v_id = 1581, hm = 1586, tt = 1584, nd = 1585, node = 264, q = 4145, p = 5274, sets = { GAFE.SET_ID.ArmorofTruth, GAFE.SET_ID.NetchsTouch, GAFE.SET_ID.StrengthoftheAutomaton } },
  { normal = GAFE.ACTIVITY_ID.NormalDarkshadeCavernsII, n_id = 1587,  veteran = GAFE.ACTIVITY_ID.VeteranDarkshadeCavernsII, v_id = 464,  hm = 467,  tt = 465,  nd = 1588, node = 198, q = 4641, p = 5275, sets = { GAFE.SET_ID.ArmorofTruth, GAFE.SET_ID.NetchsTouch, GAFE.SET_ID.StrengthoftheAutomaton } },
  { normal = GAFE.ACTIVITY_ID.NormalEldenHollowI,       n_id = 11,    veteran = GAFE.ACTIVITY_ID.VeteranEldenHollowI,       v_id = 1573, hm = 1578, tt = 1576, nd = 1577, node = 191, q = 4336, p = 5276, sets = { GAFE.SET_ID.Barkskin, GAFE.SET_ID.LightSpeaker, GAFE.SET_ID.UndauntedBastion } },
  { normal = GAFE.ACTIVITY_ID.NormalEldenHollowII,      n_id = 1579,  veteran = GAFE.ACTIVITY_ID.VeteranEldenHollowII,      v_id = 459,  hm = 463,  tt = 461,  nd = 1580, node = 265, q = 4675, p = 5277, sets = { GAFE.SET_ID.Barkskin, GAFE.SET_ID.LightSpeaker, GAFE.SET_ID.UndauntedBastion } },
  { normal = GAFE.ACTIVITY_ID.NormalWayrestSewersI,     n_id = 79,    veteran = GAFE.ACTIVITY_ID.VeteranWayrestSewersI,     v_id = 1589, hm = 1594, tt = 1592, nd = 1593, node = 189, q = 4246, p = 5278, sets = { GAFE.SET_ID.CombatPhysician, GAFE.SET_ID.SergeantsMail, GAFE.SET_ID.Toothrow } },
  { normal = GAFE.ACTIVITY_ID.NormalWayrestSewersII,    n_id = 1595,  veteran = GAFE.ACTIVITY_ID.VeteranWayrestSewersII,    v_id = 678,  hm = 681,  tt = 679,  nd = 1596, node = 263, q = 4813, p = 5282, sets = { GAFE.SET_ID.CombatPhysician, GAFE.SET_ID.SergeantsMail, GAFE.SET_ID.Toothrow } },
  { normal = GAFE.ACTIVITY_ID.NormalArxCorinium,        n_id = 272,   veteran = GAFE.ACTIVITY_ID.VeteranArxCorinium,        v_id = 1604, hm = 1609, tt = 1607, nd = 1608, node = 192, q = 4202, p = 5288, sets = { GAFE.SET_ID.LamiasSong, GAFE.SET_ID.Medusa, GAFE.SET_ID.UndauntedInfiltrator } },
  { normal = GAFE.ACTIVITY_ID.NormalCityOfAshI,         n_id = 551,   veteran = GAFE.ACTIVITY_ID.VeteranCityOfAshI,         v_id = 1597, hm = 1602, tt = 1600, nd = 1601, node = 197, q = 4778, p = 5290, sets = { GAFE.SET_ID.BurningSpellweave, GAFE.SET_ID.Embershield, GAFE.SET_ID.Sunderflame } },
  { normal = GAFE.ACTIVITY_ID.NormalCityOfAshII,        n_id = 1603,  veteran = GAFE.ACTIVITY_ID.VeteranCityOfAshII,        v_id = 878,  hm = 1114, tt = 1108, nd = 1107, node = 268, q = 5120, p = 5381, sets = { GAFE.SET_ID.BurningSpellweave, GAFE.SET_ID.Embershield, GAFE.SET_ID.Sunderflame } },
  { normal = GAFE.ACTIVITY_ID.NormalCryptOfHeartsI,     n_id = 80,    veteran = GAFE.ACTIVITY_ID.VeteranCryptOfHeartsI,     v_id = 1610, hm = 1615, tt = 1613, nd = 1614, node = 190, q = 4379, p = 5283, sets = { GAFE.SET_ID.EbonArmory, GAFE.SET_ID.Leviathan, GAFE.SET_ID.ShroudoftheLich } },
  { normal = GAFE.ACTIVITY_ID.NormalCryptOfHeartsII,    n_id = 1616,  veteran = GAFE.ACTIVITY_ID.VeteranCryptOfHeartsII,    v_id = 876,  hm = 1084, tt = 941,  nd = 942,  node = 269, q = 5113, p = 5284, sets = { GAFE.SET_ID.EbonArmory, GAFE.SET_ID.Leviathan, GAFE.SET_ID.ShroudoftheLich } },
  -- DLC
  { normal = GAFE.ACTIVITY_ID.NormalDirefrostKeep,      n_id = 357,   veteran = GAFE.ACTIVITY_ID.VeteranDirefrostKeep,      v_id = 1623, hm = 1628, tt = 1626, nd = 1627, node = 195, q = 4346, p = 5291, sets = { GAFE.SET_ID.DraugrHulk, GAFE.SET_ID.MagickaFurnace, GAFE.SET_ID.TheIceFurnace } },
  { normal = GAFE.ACTIVITY_ID.NormalTempestIsland,      n_id = 81,    veteran = GAFE.ACTIVITY_ID.VeteranTempestIsland,      v_id = 1617, hm = 1622, tt = 1620, nd = 1621, node = 188, q = 4538, p = 5301, sets = { GAFE.SET_ID.JoltingArms, GAFE.SET_ID.OverwhelmingSurge, GAFE.SET_ID.StormMaster } },
  { normal = GAFE.ACTIVITY_ID.NormalVolenfell,          n_id = 391,   veteran = GAFE.ACTIVITY_ID.VeteranVolenfell,          v_id = 1629, hm = 1634, tt = 1632, nd = 1633, node = 196, q = 4432, p = 5303, sets = { GAFE.SET_ID.Crusader, GAFE.SET_ID.DunerippersScales, GAFE.SET_ID.TreasureHunter } },
  { normal = GAFE.ACTIVITY_ID.NormalBlackheartHaven,    n_id = 410,   veteran = GAFE.ACTIVITY_ID.VeteranBlackheartHaven,    v_id = 1647, hm = 1652, tt = 1650, nd = 1651, node = 186, q = 4589, p = 5305, sets = { GAFE.SET_ID.BonePiratesTatters, GAFE.SET_ID.KnightErrantsMail, GAFE.SET_ID.UndauntedUnweaver } },
  { normal = GAFE.ACTIVITY_ID.NormalBlessedCrucible,    n_id = 393,   veteran = GAFE.ACTIVITY_ID.VeteranBlessedCrucible,    v_id = 1641, hm = 1646, tt = 1644, nd = 1645, node = 187, q = 4469, p = 5306, sets = { GAFE.SET_ID.NikulasHeavyArmor, GAFE.SET_ID.NobleDuelistsSilks, GAFE.SET_ID.SwordDancer } },
  { normal = GAFE.ACTIVITY_ID.NormalSelenesWeb,         n_id = 417,   veteran = GAFE.ACTIVITY_ID.VeteranSelenesWeb,         v_id = 1635, hm = 1640, tt = 1638, nd = 1639, node = 185, q = 4733, p = 5307, sets = { GAFE.SET_ID.DuroksBane, GAFE.SET_ID.HircinesVeneer, GAFE.SET_ID.VestmentsoftheWarlock } },
  { normal = GAFE.ACTIVITY_ID.NormalVaultsOfMadness,    n_id = 570,   veteran = GAFE.ACTIVITY_ID.VeteranVaultsOfMadness,    v_id = 1653, hm = 1658, tt = 1656, nd = 1657, node = 184, q = 4822, p = 5309, sets = { GAFE.SET_ID.OblivionsEdge, GAFE.SET_ID.Rattlecage, GAFE.SET_ID.TheWormsRaiment } },
  { normal = GAFE.ACTIVITY_ID.NormalBalSunnar,          n_id = 3468,  veteran = GAFE.ACTIVITY_ID.VeteranBalSunnar,          v_id = 3469, hm = 3470, tt = 3471, nd = 3472, node = 531, q = 6896, p = 6897, sets = { GAFE.SET_ID.NixHoundsHowl, GAFE.SET_ID.RitemastersBond, GAFE.SET_ID.TelvanniEnforcer } },
  { normal = GAFE.ACTIVITY_ID.NormalBedlamVeil,         n_id = 3851,  veteran = GAFE.ACTIVITY_ID.VeteranBedlamVeil,         v_id = 3852, hm = 3853, tt = 3854, nd = 3855, node = 565, q = 7155, p = 7156, sets = { GAFE.SET_ID.BlindPathInduction, GAFE.SET_ID.ReflectedFury, GAFE.SET_ID.TarnishedNightmare } },
  { normal = GAFE.ACTIVITY_ID.NormalBlackDrakeVilla,    n_id = 2831,  veteran = GAFE.ACTIVITY_ID.VeteranBlackDrakeVilla,    v_id = 2832, hm = 2833, tt = 2834, nd = 2835, node = 437, q = 6576, p = 6577, sets = { GAFE.SET_ID.DrakesRush, GAFE.SET_ID.KinrassWrath, GAFE.SET_ID.TrueSwornFury } },
  { normal = GAFE.ACTIVITY_ID.NormalBlackGemFoundry,    n_id = 4334,  veteran = GAFE.ACTIVITY_ID.VeteranBlackGemFoundry,    v_id = 4335, hm = 4336, tt = 4337, nd = 4338, node = 605, q = 7323, p = 7324, sets = { GAFE.SET_ID.BlackFoundrySteel, GAFE.SET_ID.LustrousSoulwell, GAFE.SET_ID.VykandsSoulfury } },
  { normal = GAFE.ACTIVITY_ID.NormalBloodrootForge,     n_id = 1690,  veteran = GAFE.ACTIVITY_ID.VeteranBloodrootForge,     v_id = 1691, hm = 1696, tt = 1694, nd = 1695, node = 326, q = 5889, p = 6053, sets = { GAFE.SET_ID.Blooddrinker, GAFE.SET_ID.FlameBlossom, GAFE.SET_ID.HagravensGarden } },
  { normal = GAFE.ACTIVITY_ID.NormalCastleThorn,        n_id = 2704,  veteran = GAFE.ACTIVITY_ID.VeteranCastleThorn,        v_id = 2705, hm = 2706, tt = 2707, nd = 2708, node = 436, q = 6507, p = 6508, sets = { GAFE.SET_ID.CrimsonTwilight, GAFE.SET_ID.TalfygsTreachery, GAFE.SET_ID.UnleashedTerror } },
  { normal = GAFE.ACTIVITY_ID.NormalCoralAerie,         n_id = 3104,  veteran = GAFE.ACTIVITY_ID.VeteranCoralAerie,         v_id = 3105, hm = 3153, tt = 3107, nd = 3108, node = 497, q = 6740, p = 6741, sets = { GAFE.SET_ID.GlacialGuardian, GAFE.SET_ID.GryphonsReprisal, GAFE.SET_ID.MaligaligsMaelstrom } },
  { normal = GAFE.ACTIVITY_ID.NormalCradleOfShadows,    n_id = 1522,  veteran = GAFE.ACTIVITY_ID.VeteranCradleOfShadows,    v_id = 1523, hm = 1524, tt = 1525, nd = 1526, node = 261, q = 5702, p = 5780, sets = { GAFE.SET_ID.Gossamer, GAFE.SET_ID.HandofMephala, GAFE.SET_ID.Widowmaker } },
  { normal = GAFE.ACTIVITY_ID.NormalDepthsOfMalatar,    n_id = 2270,  veteran = GAFE.ACTIVITY_ID.VeteranDepthsOfMalatar,    v_id = 2271, hm = 2272, tt = 2273, nd = 2274, node = 390, q = 6251, p = 6252, sets = { GAFE.SET_ID.AuroransThunder, GAFE.SET_ID.FrozenWatcher, GAFE.SET_ID.ScavengingDemise } },
  { normal = GAFE.ACTIVITY_ID.NormalEarthenRootEnclave, n_id = 3375,  veteran = GAFE.ACTIVITY_ID.VeteranEarthenRootEnclave, v_id = 3376, hm = 3377, tt = 3378, nd = 3379, node = 520, q = 6835, p = 6836, sets = { GAFE.SET_ID.DeeprootZeal, GAFE.SET_ID.RageOfTheUrsauk, GAFE.SET_ID.StonesAccord } },
  { normal = GAFE.ACTIVITY_ID.NormalExiledRedbout,      n_id = 4109,  veteran = GAFE.ACTIVITY_ID.VeteranExiledRedbout,      v_id = 4110, hm = 4111, tt = 4112, nd = 4113, node = 581, q = 7235, p = 7236, sets = { GAFE.SET_ID.JerensisBladestorm, GAFE.SET_ID.LucillasWindshield, GAFE.SET_ID.VandorallensResonance } },
  { normal = GAFE.ACTIVITY_ID.NormalFalkreathHold,      n_id = 1698,  veteran = GAFE.ACTIVITY_ID.VeteranFalkreathHold,      v_id = 1699, hm = 1704, tt = 1702, nd = 1703, node = 332, q = 5891, p = 6054, sets = { GAFE.SET_ID.DraugrsRest, GAFE.SET_ID.Ironblood, GAFE.SET_ID.PillarofNirn } },
  { normal = GAFE.ACTIVITY_ID.NormalFangLair,           n_id = 1959,  veteran = GAFE.ACTIVITY_ID.VeteranFangLair,           v_id = 1960, hm = 1965, tt = 1963, nd = 1964, node = 341, q = 6064, p = 6155, sets = { GAFE.SET_ID.CaluurionsLegacy, GAFE.SET_ID.TrappingsofInvigoration, GAFE.SET_ID.UlfnorsFavor } },
  { normal = GAFE.ACTIVITY_ID.NormalFrostvault,         n_id = 2260,  veteran = GAFE.ACTIVITY_ID.VeteranFrostvault,         v_id = 2261, hm = 2262, tt = 2263, nd = 2264, node = 389, q = 6249, p = 6250, sets = { GAFE.SET_ID.IcyConjuror, GAFE.SET_ID.MightyGlacier, GAFE.SET_ID.TzogvinsWarband } },
  { normal = GAFE.ACTIVITY_ID.NormalGravenDeep,         n_id = 3394,  veteran = GAFE.ACTIVITY_ID.VeteranGravenDeep,         v_id = 3395, hm = 3396, tt = 3397, nd = 3398, node = 521, q = 6837, p = 6838, sets = { GAFE.SET_ID.GraveInevitability, GAFE.SET_ID.PangritDenmother, GAFE.SET_ID.PhylacterysGrasp } },
  { normal = GAFE.ACTIVITY_ID.NormalIcereach,           n_id = 2539,  veteran = GAFE.ACTIVITY_ID.VeteranIcereach,           v_id = 2540, hm = 2541, tt = 2542, nd = 2543, node = 424, q = 6414, p = 6415, sets = { GAFE.SET_ID.BanisTorment, GAFE.SET_ID.HitisHearth, GAFE.SET_ID.TitanbornStrength } },
  { normal = GAFE.ACTIVITY_ID.NormalImperialCityPrison, n_id = 1345,  veteran = GAFE.ACTIVITY_ID.VeteranImperialCityPrison, v_id = 880,  hm = 1303, tt = 1128, nd = 1129, node = 236, q = 5136, p = 5382, sets = { GAFE.SET_ID.LeechingPlate, GAFE.SET_ID.ScathingMage, GAFE.SET_ID.SheerVenom } },
  { normal = GAFE.ACTIVITY_ID.NormalLairOfMaarselok,    n_id = 2425,  veteran = GAFE.ACTIVITY_ID.VeteranLairOfMaarselok,    v_id = 2426, hm = 2427, tt = 2428, nd = 2429, node = 398, q = 6351, p = 6352, sets = { GAFE.SET_ID.AzureblightReaper, GAFE.SET_ID.DragonsDefilement, GAFE.SET_ID.ZensRedress } },
  { normal = GAFE.ACTIVITY_ID.NormalLepScluse,          n_id = 4128,  veteran = GAFE.ACTIVITY_ID.VeteranLepScluse,          v_id = 4129, hm = 4130, tt = 4131, nd = 4132, node = 582, q = 7237, p = 7238, sets = { GAFE.SET_ID.FledglingsNest, GAFE.SET_ID.HeroicUnity, GAFE.SET_ID.NoxiousBoulder } },
  { normal = GAFE.ACTIVITY_ID.NormalMarchOfSacrifices,  n_id = 2162,  veteran = GAFE.ACTIVITY_ID.VeteranMarchOfSacrifices,  v_id = 2163, hm = 2164, tt = 2165, nd = 2166, node = 370, q = 6188, p = 6189, sets = { GAFE.SET_ID.BloodMoon, GAFE.SET_ID.HanusCompassion, GAFE.SET_ID.HavenofUrsus } },
  { normal = GAFE.ACTIVITY_ID.NormalMoonHunterKeep,     n_id = 2152,  veteran = GAFE.ACTIVITY_ID.VeteranMoonHunterKeep,     v_id = 2153, hm = 2154, tt = 2155, nd = 2156, node = 371, q = 6186, p = 6187, sets = { GAFE.SET_ID.JailersTenacity, GAFE.SET_ID.MoonHunter, GAFE.SET_ID.SavageWerewolf } },
  { normal = GAFE.ACTIVITY_ID.NormalMoongraveFane,      n_id = 2415,  veteran = GAFE.ACTIVITY_ID.VeteranMoongraveFane,      v_id = 2416, hm = 2417, tt = 2418, nd = 2419, node = 391, q = 6349, p = 6350, sets = { GAFE.SET_ID.DroZakarsClaws, GAFE.SET_ID.HollowfangThirst, GAFE.SET_ID.RenaldsResolve } },
  { normal = GAFE.ACTIVITY_ID.NormalNajCaldeesh,        n_id = 4311,  veteran = GAFE.ACTIVITY_ID.VeteranNajCaldeesh,        v_id = 4312, hm = 4313, tt = 4314, nd = 4315, node = 606, q = 7320, p = 7321, sets = { GAFE.SET_ID.StonehulkDomination, GAFE.SET_ID.ToolsOfTheTrapmaster, GAFE.SET_ID.XanmeerSpellweaver } },
  { normal = GAFE.ACTIVITY_ID.NormalOathswornPit,       n_id = 3810,  veteran = GAFE.ACTIVITY_ID.VeteranOathswornPit,       v_id = 3811, hm = 3812, tt = 3813, nd = 3814, node = 556, q = 7105, p = 7106, sets = { GAFE.SET_ID.BlackGloveGrounding, GAFE.SET_ID.CindersOfAnthelmir, GAFE.SET_ID.SluthrugsHunger } },
  { normal = GAFE.ACTIVITY_ID.NormalRedPetalBastion,    n_id = 3016,  veteran = GAFE.ACTIVITY_ID.VeteranRedPetalBastion,    v_id = 3017, hm = 3087, tt = 3019, nd = 3020, node = 470, q = 6683, p = 6684, sets = { GAFE.SET_ID.GrislyGourmet, GAFE.SET_ID.ThunderCaller, GAFE.SET_ID.SilverRoseVigil } },
  { normal = GAFE.ACTIVITY_ID.NormalRuinsOfMazzatun,    n_id = 1504,  veteran = GAFE.ACTIVITY_ID.VeteranRuinsOfMazzatun,    v_id = 1505, hm = 1506, tt = 1507, nd = 1508, node = 260, q = 5403, p = 5636, sets = { GAFE.SET_ID.AmberPlasm, GAFE.SET_ID.AspectofMazzatun, GAFE.SET_ID.HeemJasRetribution } },
  { normal = GAFE.ACTIVITY_ID.NormalScalecallerPeak,    n_id = 1975,  veteran = GAFE.ACTIVITY_ID.VeteranScalecallerPeak,    v_id = 1976, hm = 1981, tt = 1979, nd = 1980, node = 363, q = 6065, p = 6154, sets = { GAFE.SET_ID.CurseofDoylemish, GAFE.SET_ID.JorvuldsGuidance, GAFE.SET_ID.PlagueSlinger } },
  { normal = GAFE.ACTIVITY_ID.NormalScrivenersHall,     n_id = 3529,  veteran = GAFE.ACTIVITY_ID.VeteranScrivenersHall,     v_id = 3530, hm = 3531, tt = 3532, nd = 3533, node = 532, q = 7027, p = 7028, sets = { GAFE.SET_ID.AbyssalBrace, GAFE.SET_ID.ApocryphalInspiration, GAFE.SET_ID.RunecarversBlaze } },
  { normal = GAFE.ACTIVITY_ID.NormalShipwrightsRegret,  n_id = 3114,  veteran = GAFE.ACTIVITY_ID.VeteranShipwrightsRegret,  v_id = 3115, hm = 3117, tt = 3117, nd = 3118, node = 498, q = 6742, p = 6743, sets = { GAFE.SET_ID.SpriggansVigor, GAFE.SET_ID.StormCursedsRevenge, GAFE.SET_ID.TurningTide } },
  { normal = GAFE.ACTIVITY_ID.NormalStoneGarden,        n_id = 2694,  veteran = GAFE.ACTIVITY_ID.VeteranStoneGarden,        v_id = 2695, hm = 2755, tt = 2697, nd = 2698, node = 435, q = 6505, p = 6506, sets = { GAFE.SET_ID.ArkasissGenius, GAFE.SET_ID.ElementalCatalyst, GAFE.SET_ID.KraglensHowl } },
  { normal = GAFE.ACTIVITY_ID.NormalCauldron,           n_id = 2841,  veteran = GAFE.ACTIVITY_ID.VeteranCauldron,           v_id = 2842, hm = 2843, tt = 2844, nd = 2845, node = 454, q = 6578, p = 6579, sets = { GAFE.SET_ID.DagonsDominion, GAFE.SET_ID.FoolkillersWard, GAFE.SET_ID.UnleashedRitualist } },
  { normal = GAFE.ACTIVITY_ID.NormalDreadCellar,        n_id = 3026,  veteran = GAFE.ACTIVITY_ID.VeteranDreadCellar,        v_id = 3027, hm = 3028, tt = 3029, nd = 3030, node = 469, q = 6685, p = 6686, sets = { GAFE.SET_ID.CrimsonOathsRive, GAFE.SET_ID.RushofAgony, GAFE.SET_ID.ScorionsFeast } },
  { normal = GAFE.ACTIVITY_ID.NormalUnhallowedGrave,    n_id = 2549,  veteran = GAFE.ACTIVITY_ID.VeteranUnhallowedGrave,    v_id = 2550, hm = 2551, tt = 2552, nd = 2553, node = 425, q = 6416, p = 6417, sets = { GAFE.SET_ID.AegisCaller, GAFE.SET_ID.DraugrkinsGrip, GAFE.SET_ID.GraveGuardian } },
  { normal = GAFE.ACTIVITY_ID.NormalWhiteGoldTower,     n_id = 1346,  veteran = GAFE.ACTIVITY_ID.VeteranWhiteGoldTower,     v_id = 1120, hm = 1279, tt = 1275, nd = 1276, node = 247, q = 5342, p = 5431, sets = { GAFE.SET_ID.BrandsofImperium, GAFE.SET_ID.EssenceThief, GAFE.SET_ID.SpellPowerCure } },
}

local DUNGEONS_ACTIVITY_DATA = {}
for _, d in ipairs(DUNGEON_CONFIGS) do
  DUNGEONS_ACTIVITY_DATA[d.normal]  = { id = d.n_id, node = d.node, q = d.q, p = d.p, hm = false,  tt = false,  nd = false,  sets = d.sets }
  DUNGEONS_ACTIVITY_DATA[d.veteran] = { id = d.v_id, node = d.node, q = d.q, p = d.p, hm = d.hm,   tt = d.tt,   nd = d.nd,   sets = d.sets }
end

GAFE.DUNGEONS_ACTIVITY_DATA = DUNGEONS_ACTIVITY_DATA
